WIP! - custom OSM server config for docker-compose
hotosm/tasking-manager pull request #3060
Opened 2020-05-30 22:20 UTC by majdal

**Note** This is work in progress - just opened the PR to make sure that I'm starting on the right foot. I'm not sure if this is good practice or not, so feel free to close and I'll re-open when I'm further along. 

Meant to address #2865 

A question though: Shall I also change the names in the user messages? e.g. the welcome message at: `backend/services/messaging/templates/welcome_message_en.txt`

2020-05-30 22:49 UTC, JorgeMartinezG commented
I like this

2020-05-31 00:37 UTC, majdal commented
Should also be checked against #2816 (docker improvements branch)

2020-09-03 15:35 UTC, geohacker commented
Hi @majdal @willemarcel! Thanks so much @majdal for your work on this so far. This feature will be very useful for us as I'm planning to add TM4 into [osm-seed](https://github.com/developmentseed/osm-seed/). Primarily to be used within openhistoricalmap.org.

@willemarcel Could be perhaps put this for release soon? 
@majdal looks like you have completed most of what's needed. Do you need me to look at anything specific?

2020-09-03 21:16 UTC, majdal commented
@geohacker there might be some more work to do after #2816 was merged, I can check next week maybe!

2020-09-03 23:11 UTC, willemarcel requested changes
@majdal let us know if you need help to fix the issues

2020-09-03 23:11 UTC, willemarcel commented on frontend/src/components/header/messages.js
> +    defaultMessage: `Have you finished the registration on ${TM_ORG_NAME}?`,
Inserting env vars on react-intl messages will generate a mess, and TM_ORG_NAME here is the organization that is deploying the TM instance (on HOT case it is "Humanitarian OpenStreetMap Team"). In my opinion, we should continue using OpenStreetMap. When you are deploying TM in a context of another OSM server, you will have the OpenStreetMap website with the same name, wouldn't you?

2020-09-03 23:11 UTC, willemarcel commented on frontend/src/utils/editorsList.js
> +      url: `${OSM_SERVER_URL}&`,
OSM_SERVER_URL, ID_EDITOR_URL and POTLATCH2_EDITOR_URL are not being exported from `../config`

2020-09-04 11:48 UTC, geohacker commented
@willemarcel I pulled @majdal's work and addressed your comments in https://github.com/hotosm/tasking-manager/pull/3564 — hope that's alright!

2020-09-07 21:53 UTC, closed without merging