Added file dropdown feature to map creation
hotosm/tasking-manager pull request #3769
Opened 2020-10-23 09:00 UTC by sumukhah

fixes: #2437

Please have a detailed look before merging. Users can drag and drop on either on the map or on the Input field

![Peek 2020-10-23 14-25](https://user-images.githubusercontent.com/23723464/96978496-0cafc900-153c-11eb-86db-2ba54229b2cb.gif)

2020-10-24 21:24 UTC, willemarcel commented
Thanks, @sumukhah! Would you mind rebasing it? Before you created that one I have made some improvements over your #3762

2020-10-29 15:08 UTC, sumukhah commented
@willemarcel, Can you review now pls?

2020-10-30 13:53 UTC, willemarcel requested changes
Thanks a lot, @sumukhah. We need a little change before merging it.

2020-10-30 13:53 UTC, willemarcel commented on frontend/src/components/projectCreate/projectCreationMap.js
> +  const { getRootProps, getInputProps } = useDropzone({ onDrop: uploadFile });
@sumukhah you should use here the same dropzone config that I used on SetAoi. Your config doesn't allow us to draw on the map.

2020-11-02 12:32 UTC, willemarcel commented
@sumukhah one additional changes needed: the drag and drop upload should be enabled only on the step 1.

2020-11-03 21:22 UTC, willemarcel commented
@sumukhah I made the change! I'll review it more carefully and merge very soon! Thanks a lot!

2020-11-03 21:22 UTC, willemarcel approved these changes

2020-11-05 19:32 UTC, merged

2020-11-06 13:41 UTC, sumukhah commented
Thank you @willemarcel