Refactor Campaign Service and Campaign static methods
hotosm/tasking-manager pull request #3893
Opened 2020-11-19 07:16 UTC by d-rita

**What does this PR do?**
This PR refactors the Campaign and Campaign Service static methods.

**Steps Taken:** 
- Add a new static method in the Organisation Service class to get all the organisations under a campaign
- Add a new static method to convert a collection of campaigns to a List DTO
- Move replicated static methods from the Campaign model to the Campaign Service class
- Refactor methods to make use of newly added ones.

**Some of the URLs to test:**
1) Via Postman. Method: `GET`. 
- `http://127.0.0.1:5000/api/v2/campaigns/`
- `http://127.0.0.1:5000/api/v2/campaigns/<int:campaign_id>/`
- `http://127.0.0.1:5000/api/v2/organisations/<int:organisation_id>/campaigns/`
- `http://127.0.0.1:5000/api/v2/projects/<int:project_id>/campaigns/`
2) Frontend
- `http://localhost:3000/manage/campaigns/`
- `http://localhost:3000/manage/campaigns/<int:campaign_id>`

2020-11-19 20:29 UTC, willemarcel commented on backend/services/organisation_service.py
> +            if user_id != 0:
I don't know if we need that restriction. Some opinion, @ramyaragupathy ?

2020-11-19 20:30 UTC, willemarcel commented
I like the new structure. We are not supporting to assign organizations with campaigns on the frontend and we are not using that information of organizations related to a campaign.

I think the best would be to remove that organization field from the campaign detail endpoint. When we have that need we can build a new endpoint: `/api/v2/campaigns/<int:campaign_id>/organisations/`

2020-11-20 01:20 UTC, willemarcel requested changes
comment above

2020-11-20 12:30 UTC, d-rita commented
> comment above

2020-11-20 21:47 UTC, willemarcel approved these changes
Awesome! Thanks!

2020-11-30 10:30 UTC, merged