Allow validators to view the history of multiple tasks
hotosm/tasking-manager pull request #4013
Opened 2020-12-24 11:16 UTC by d-rita

**What does this PR do?** 
Resolves #3730

2020-12-28 07:45 UTC, ramyaragupathy reviewed
@d-rita @willemarcel - 
* [x] Multiple task history loads beautifully, while locking more than one task for validation 💯 
* [x]  Verified the API call made to fetch task history 
* [ ] Unclear about the usage of red square icons with label `Comments` and `Activities`

![image](https://user-images.githubusercontent.com/12103383/103194689-749cda00-4906-11eb-91e0-15f43a8e08a3.png)

2020-12-28 10:14 UTC, willemarcel requested changes
@d-rita thanks! The behaviour is perfect. Some suggestions to improve the style and code:

![image](https://user-images.githubusercontent.com/666291/103206908-c5e3a400-48db-11eb-8cd5-dc2ec71f55e1.png)
We could reduce the space between the button and the content.

2020-12-28 10:14 UTC, willemarcel commented on frontend/src/assets/styles/_accordion.scss
> +.accordion {
Most of those CSS rules are available on Tachyons, would it be possible to use them on the component and only define the ones that are missing? I believe only the animation classes are missing. The font size of the accordion button could be a bit small (1rem / f6 on tachyons)

2020-12-28 10:14 UTC, willemarcel commented on frontend/src/components/taskSelection/action.js
> +      for (let i = 0; i < taskIds.length; i++) {
I suggest you to `use taskIds.forEach()` instead of the for statement.

2020-12-28 10:14 UTC, willemarcel commented on frontend/src/components/taskSelection/action.js
> +                                <FormattedMessage {...messages.task} />
It's better to use `<FormattedMessage {...messages.taskActivity} values={{n: t.taskId}} />`

2020-12-28 10:14 UTC, willemarcel commented on frontend/src/assets/styles/_accordion.scss
> +        background-color: #ddd;
I didn't like that hover effect, I think it's calling too much attention.

2020-12-28 10:14 UTC, willemarcel commented on frontend/src/components/taskSelection/action.js
> +                      <Accordion allowMultipleExpanded allowZeroExpanded onChange={handleFetch}>
We could move that component to a new file. That action.js is too big already. We can also write tests to it as it's isolated.

2020-12-28 10:15 UTC, willemarcel commented
> Unclear about the usage of red square icons with label Comments and Activities

@ramyaragupathy this is our default checkbox style

2020-12-29 10:54 UTC, willemarcel commented on frontend/src/components/taskSelection/action.js
> +      if (Object.keys(multipleTasksInfo).indexOf(id.toString()) < 0) {
`Object.keys(multipleTasksInfo).includes(id.toString())` is more expressive and straightforward.'

2021-01-04 10:59 UTC, willemarcel approved these changes
Just made a little change on the chevron icon size and renamed some files.

2021-01-04 11:17 UTC, merged