Refactor duplicated components - server and error messages
hotosm/tasking-manager pull request #4452
Opened 2021-03-29 20:34 UTC by d-rita

Fixes #4376

2021-03-30 19:53 UTC, willemarcel requested changes
I think we can go a bit deeper on this refactoring. Some additional things we can do:
- handle the API requests on the Create / Edit campaign components with the new useAsync
- Remove the error message after the input field change
- In both cases, we are calling Error Message with the same children. It's not clear how the return should change because of the `error` argument. Try to make it easier to understand.

If you want we can schedule a session to pair on it.

2021-03-30 19:53 UTC, willemarcel commented on frontend/src/components/responseMessages.js
> +export const ErrorMessage = ({ error, success, children }) => {
The `success` argument is not being used

2021-04-20 01:22 UTC, willemarcel approved these changes
@d-rita I could disable the error alert when the form gets dirty, and I also improved the style of the Error Alert.

2021-04-20 11:33 UTC, d-rita reviewed
Looks good @willemarcel

2021-04-20 11:35 UTC, merged