Update docker-compose and other docker files
hotosm/tasking-manager pull request #4646
Opened 2021-05-13 15:37 UTC by tsmock

* Update `Makefile` so it works (`app` -> `backend`/`frontend`, depending upon context)
* Use an official postgis image (that is actually updated, `mdillon/postgis:11` -> `postgis/postgis:11-3.1` (3.1 is the postgis version)
* Use official node images (`tiangolo/node-frontend:10` -> `node:14` (node 10 is no longer supported, and node 12 EOL is less than a year away).

2021-05-13 17:45 UTC, willemarcel commented
Thanks, @tsmock!! @d-rita Could you review it when you have the possibility?

2023-06-21 08:42 UTC, eternaltyro requested changes
Now that we have tested later versions of Node and Postgres (and Postgis), we can safely upgrade version tags for both of them. 

When that's done, this PR is good to go.

2023-06-21 08:42 UTC, eternaltyro commented on docker-compose.yml
> +    image: postgis/postgis:11-3.1
We can now safely use [postgis/postgis:14-3.3](https://registry.hub.docker.com/r/postgis/postgis/tags?page=1&name=14-3.3)

2023-06-21 08:42 UTC, eternaltyro commented on scripts/docker/Dockerfile.frontend
> +FROM node:14 as build
We can upgrade node version to 16 as well.

2023-06-21 08:42 UTC, eternaltyro commented on scripts/docker/Dockerfile.frontend_development
> +FROM node:14 as build
node 16 here too.

2023-06-23 13:43 UTC, tsmock commented
I need to do some fiddling. It has been awhile since I made this PR, so I need to reverify everything.

2023-08-03 12:44 UTC, tsmock commented
I don't remember if I decided it was ready or not. I'll rebase onto current dev and see if it all works.

I got distracted by some other stuff (mostly going through dependencies on the frontend or working on JOSM).

2023-08-03 13:55 UTC, tsmock commented
OK. I've been going over some of the code:
* I _think_ `HEALTHCHECK --interval=60s --start-period=15s CMD ["curl", "-f", "http://localhost:8000/api/v2/system/heartbeat/", "||", "exit", "1"]` will work, but I haven't verified it.

`podman-compose up` is working properly insofar as starting everything. I probably messed up the network configuration (I wasn't able to connect).

2023-08-04 04:52 UTC, Aadesh-Baral commented
> podman-compose up is working properly insofar as starting everything. I probably messed up the network configuration (I wasn't able to connect).

Could you please clarify where you were unable to connect?

2023-08-04 04:52 UTC, Aadesh-Baral commented
> podman-compose up is working properly insofar as starting everything. I probably messed up the network configuration (I wasn't able to connect).

Could you please clarify where you were unable to connect?

2023-08-16 13:10 UTC, dakotabenjamin commented
@tsmock on the HEALTHCHECK, `docker compose` runs the frontend/backend on port 80. In addition, I needed to change the following to get it to work: 
```
diff --git a/docker-compose.yml b/docker-compose.yml
index 31f1db1f..bfcfb9cb 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -59,4 +59,4 @@ services:
 
 networks:
   tm-web:
-    external: true
+    external: false
```

This doesn't have to do with your PR, I'm not even really sure why it was set as external in the first place. I think the docs for running/developing with Docker sorely need updating, but I don't think we need to require that to merge this PR. With the two changes suggested above, I think this is good to go, and we can follow up with a cleanup/clarity PR.

2023-08-21 20:17 UTC, dakotabenjamin approved these changes
LGTM

2023-08-29 13:15 UTC, merged