make docker defaults more useful for local testing setup and update documentation
hotosm/tasking-manager pull request #5087
Opened 2022-04-09 19:51 UTC by SlowMo24

closes #5008

2022-04-09 21:00 UTC, SlowMo24 commented
sorry created this PR prematurely. Will rework and eventually reopen

2022-06-16 05:04 UTC, Aadesh-Baral commented
Hi, @SlowMo24 we are working to implement OAuth2.0 for OSM login on #5029 which will have some changes to setup TM. Will review it as soon as #5029 is merged.

2022-08-21 05:17 UTC, Aadesh-Baral requested changes
I think that adding frontend/backend URL instructions with and without docker to example.env would be useful. Other than that looks good to me.

2022-08-21 05:17 UTC, Aadesh-Baral commented on example.env
> +# On development instances it should be http://localhost:80
```suggestion
# On development instances it should be 127.0.0.1:3000 or localhost:3000
# While setting up using `docker-compose` it should be http://localhost:80
```

2022-08-21 05:17 UTC, Aadesh-Baral commented on example.env
> +TM_APP_BASE_URL=http://localhost:80
```suggestion
TM_APP_BASE_URL=http://127.0.0.1:3000
```

2022-08-21 05:17 UTC, Aadesh-Baral commented on example.env
> +# On development instances it should be http://localhost:80
```suggestion
# On development instances it should be 127.0.0.1:5000 or localhost:5000
# While setting up using `docker-compose` it should be http://localhost:80
```

2022-08-21 05:17 UTC, Aadesh-Baral commented on example.env
> +TM_APP_API_URL=http://localhost:80
```suggestion
TM_APP_API_URL=http://127.0.0.1:5000
```

2022-09-13 12:29 UTC, SlowMo24 commented
Thank you @Aadesh-Baral for reviewing. I have updated the config and docker-compose so it uses the same ports as the local development setup. I have also addressed #5313 and simplified the whole docker configuration. Feel free to comment.

2022-12-15 08:22 UTC, Aadesh-Baral approved these changes

2022-12-19 10:14 UTC, SlowMo24 commented
Hey, thanks for approving. I think there has been a rework of the documentation (there is now a `docs-old` folder in main) and there are merge-conflicts. Is there any action required from my side (i.e. should I have a look at the new docs?) or are you in the middle of a process there?

2022-12-19 10:27 UTC, Aadesh-Baral commented
Hi @SlowMo24 , I've picked a commit from this PR to #5463 and planning to work on that PR itself.

2023-04-14 11:03 UTC, eternaltyro commented
Related to #5705

2023-05-10 22:48 UTC, eternaltyro approved these changes
This looks good to be merged. cc : @Aadesh-Baral this seems to only affect docker-compose setups and might not interfere with other merge requests in queue. Can we proceed?

@SlowMo24 thank you very much for these changes. We will improve over them in due course, but this is a good starting point for us.

2023-05-10 22:49 UTC, eternaltyro commented
Seems like there are some conflicts after-all. I will review this tomorrow and see how we can incorporate these changes into the new docs hierarchy.

2023-05-15 10:49 UTC, Aadesh-Baral commented
> This looks good to be merged. cc : @Aadesh-Baral this seems to only affect docker-compose setups and might not interfere with other merge requests in queue. Can we proceed?

LGTM. Please go ahead.

2024-04-11 14:32 UTC, ramyaragupathy commented
@mahesh-naxa - could you please verify if some of these issues have been fixed with the recent docker PRs? cc @spwoodcock @dakotabenjamin

2024-04-11 14:52 UTC, spwoodcock commented
The actual config changes aren't required anymore - they have since been updated.

The docs in the PR were definitely useful at the time too, but I think the docs and config have changed since then, so it's hard to reconcile.

Unfortunately, it may be best to close this PR. The contribution is valuable - so sorry @SlowMo24 we didn't have the resource at the time to properly review and merge this 🙏

2024-04-12 05:13 UTC, mahesh-naxa commented
His docs specifically on how to generate OSM Auth client/secret with screenshots are helpful imo. 
Others have been addressed.

2024-04-12 07:39 UTC, SlowMo24 commented
This MR was the result of me setting up my own tasking manager instance for a research project that I presented at SotM2022: https://gitlab.gistools.geog.uni-heidelberg.de/giscience/ideal-vgi/osm-multitag . At that time I struggled quite a bit with the documentation but especially with Traefik (see #5313 ). The project is since completed and I currently don't work with it any more (:thinking: should take down that server I set up back then). So I am out of date with your code-base on the topic.

Things happen, let's move forward: I am happy to support you (I also gained a bit more knowledge on Docker and Traefik since then ;-) )

Please tell me where you could use support and I will see what I can do. For example I could run the setup procedure again with the current documentation and create issues or MRs where I fail. Yet, I would need some info on who you actually target with the documentation and the docker setup. If it is meant to be your team-documentation and should limit the [lottery factor](https://de.wikipedia.org/wiki/Truck_Number) we might think differently about it than if it was meant for what I did: random humans set up their own instance.
Or I could see If I can rebase this MR and reduce it the the parts that are still missing, if you think that is helpful.

2024-04-12 08:49 UTC, spwoodcock commented
Thanks so much for the offer @SlowMo24, very kind of you 😄

Testing our current setup and providing feedback on the config or documentation around it would be a huge help 🙏

Feel free to rebase this or create a new MR/PR as needed & we will be much quicker to review next time!

2024-04-17 20:31 UTC, closed without merging