Add related projects at the bottom of the project detail page.
hotosm/tasking-manager pull request #5632
Opened 2023-03-14 06:03 UTC by Aadesh-Baral

closes #5626

2023-03-28 10:38 UTC, Aadesh-Baral commented
To find similar projects, we analyzed the correlation between different project metadata fields and iterated through them. For instance, we observed that organizations tend to create similar projects based on their country and category. However, considering the organization for the similarity score led to the display of projects from the same organization, which affected the diversity of our displayed projects. Hence, we excluded organization as a field. Furthermore, we found some fields that didn't significantly contribute to our results, so we discarded them to enhance performance.
Then the result was tested with some test users who found it to be satisfactory.

2023-03-28 11:20 UTC, Aadesh-Baral commented
Adding @HelNershingThapa to review frontend changes and @d-rita to review backend changes.

2023-03-29 09:04 UTC, HelNershingThapa requested changes
When you click the related project card, the page should scroll to the top so that users feel like they are viewing another project when they navigate to the related project. Use the useFetch hook to fetch linked projects as well, making the component look cleaner. Other than that, LGTM, I'll pushed with the requested changes.

2023-03-29 09:06 UTC, HelNershingThapa approved these changes

2023-03-30 08:16 UTC, d-rita reviewed
@Aadesh-Baral will the limit of the projects returned always be 4? We have a limit parameter that we don't actually give the user a chance to use in the endpoint

2023-03-30 20:49 UTC, d-rita commented on backend/api/projects/resources.py
> +              default: 1
The limit parameter should be included in this part of the documentation

2023-03-30 20:58 UTC, d-rita approved these changes
Tested this, and it works as expected. The tests are good too. Overall, LGTM

2023-05-31 00:06 UTC, ramyaragupathy approved these changes
Looks good to me @Aadesh-Baral

2023-06-01 10:33 UTC, merged