Redesign Leaderboard Stats Banner
hotosm/tasking-manager pull request #6562
Opened 2024-09-11 13:55 UTC by royallsilwallz

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [x] 🧑‍💻 Refactor

## Related Issue

- Fixes #6513 

## Describe this PR

## Screenshots
**Before -**
![image](https://github.com/user-attachments/assets/1a27b3bd-280b-4166-9f39-e908d00ecbad)

Please provide screenshots of the change.

## Alternative Approaches Considered

Did you attempt any other approaches that are not documented in code?

## Review Guide

Notes for the reviewer. How to test this change?

## Checklist before requesting a review

- 📖 Read the Tasking Manager Contributing Guide: <https://github.com/hotosm/tasking-manager/blob/develop/docs/developers/contributing.md>
- 📖 Read the HOT Code of Conduct: <https://docs.hotosm.org/code-of-conduct>
- 👷‍♀️ Create small PRs. In most cases, this will be possible.
- ✅ Provide tests for your changes.
- 📝 Use descriptive commit messages.
- 📗 Update any related documentation and include any relevant screenshots.
- 🔠 Does this PR introduce or change any environment variables? If so, make sure to specify this change in the description.

## [optional] What gif best describes this PR or how it makes you feel?

2024-09-12 02:58 UTC, emi420 requested changes

2024-09-16 06:25 UTC, royallsilwallz commented on frontend/src/components/partners/customDropdown.js
> +        style={{ padding: '0.75rem 0' }}
Done !

2024-09-16 06:26 UTC, royallsilwallz commented on frontend/src/components/button.js
> +  ...rest
I've used otherProps for this.

2024-09-17 10:37 UTC, emi420 approved these changes
Looks good to me, thanks @royallsilwallz

2024-09-18 14:14 UTC, merged